templates/jb_src/config/routes.rb
Rails.application.routes.draw do

  resources :inventories
  get 'inventories/:id/mod_new', to: 'inventories#mod_new', as: :mod_new_inventory

  resources :contacts, only: [:index]

  resources :payments
  root 'root#index'

  post 'reset', to: 'query#reset'
  post 'clients_reset', to: 'clients#reset'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  post '/search', to: 'searches#create'
  get '/search', to: 'searches#show', as: :show_search

  resources :dashboards, only: [:index] do
    collection do
      get 'payment/process', to: 'dashboards#process_payment'
    end
  end

  concern :activatable do
    patch :activate
    patch :deactivate
  end


  resources :billable_services, concerns: :activatable do
    collection do
      get '/exports', to: 'billable_services#exports'
      get '/onetime', to: 'billable_services#one_time_exports'
    end
  end


  resources :settings
  resources :contacts
  resources :payments
  # resources :rates
  # resources :services
  resources :billable_services
  # resources :stats_periods
  # resources :performance_stats
  # resources :local_exchanges
  # resources :local_exchanges_north_american_exchanges
  # resources :north_american_exchanges
  # resources :rate_centers
  # resources :calls
  # resources :products, only: [:index, :show, :edit, :update, :new ]
  resources :products
  resources :invoices, only: [:index, :show]

  resources :clients do
    resource :billing, only: [:edit, :update]

    #resources :contacts, only: [:index, :phone_contact_create]
    #resources :contacts, concerns: :activatable

    resources :contacts do

      collection do
        resources :phone_contacts#, :only => [:new, :edit, :destroy]
        resources :email_contacts#, :only => [:new, :edit, :destroy]
        # resources :technical_contacts, :only => [:new, :edit, :destory]
        resources :technical_contacts
      end

    end
    resources :billable_services, concerns: :activatable, :only => [:new, :edit, :index]
    resources :invoices, only: [:index, :show]

    resources :payments

    collection do
      get 'typeahead', constraints: { format: 'json' }
    end

    resources :sites, concerns: :activatable

    # resources :calls do
    #   resources :cdrs
    # end

    # resources :incoming_cdrs, :controller => "cdrs"
    #
    # resources :outgoing_cdrs, :controller => "cdrs"

    # resources :btns do
    #
    #   resources :phones
    #
    #   get '/invoices', to: 'invoices#index'
    #   get '/invoices/:year/:month', to: 'invoices#show'
    #
    #   resources :calls
    # end

    resources :services, concerns: :activatable
    # resources :billable_services, concerns: :activatable
    resources :sites, concerns: :activatable
    resources :buildings
    # resources :callstats
    #
    # resources :stats_periods do
    #   resources :callstats
    # end
  end

  # resources :services do
  #   resources :client_services
  # end

  # resources :client_services

  resources :btns do
    collection do
      get 'typeahead', constraints: { format: 'json' }
    end

    # resources :calls
  end

  # resources :datasources do
  #   resources :calls
  #   resources :cdrs do
  #     resources :calls
  #   end
  # end

  resources :sites, concerns: :activatable

  resources :buildings

  resources :services, concerns: :activatable, path_names: { new: 'new/client/:client_id'}

  # resources :callingphones, :controller => "phones" do
  #   resources :cdrs
  # end
  #
  # resources :calledphones, :controller => "phones" do
  #   resources :cdrs
  # end

  # resources :cdrs do
  # end

  namespace :admin do
    resources :users
  end

  resources :client_line_of_businesses, only: [:update]

  namespace :api, defaults: { format: 'json' } do
      namespace :v1, constraints: { format: 'json' } do
        resources :btns, only: [], param: 'slug' do
          resources :services, only: [:index, :show], param: 'slug'
        end
      end
  end

end

templates/jb_src/app/controllers/billable_services_controller.rb
class BillableServicesController < AuthorizationController
  include Search::ControllerHelpers
  include Montbeau::ActivatableControllerHelpers

  layout 'admin_lte'

  before_action :set_billable_service, only: [:show, :edit, :update, :destroy, :remove]

  before_action :set_client, if: :has_client_id_param?

  before_action :set_btn, if: :has_btn_id_param?

  before_action :set_invoice, if: :has_invoice_id_param?

  respond_to :html

  def index
    # @billable_services = BillableService.all.page params[:page]
    @search = BillableServiceSearch.new(search_params)

    # @billable_services = @search.results.page(params[:page])
    @billable_services = @search.results.all #page(params[:page]) #Kaminari.paginate_array(@search.results).page(params[:page])
    @results_length = @billable_services.length
    @billable_services = @search.results.all.page params[:page]
    request.parameters.merge({:page => params[:page]})

    respond_with(@billable_services)
  end

  def to_csv
    CSV.generate({}) do |csv|
      csv << @billable_services_all[0].to_export_hash.keys
      @billable_services_all.each do |bs|
        csv << bs.to_export_hash.values
      end
    end
  end

  def to_onetime_csv
    CSV.generate({}) do |csv|
      csv << @billable_services_all[0].to_onetime_export_hash.keys
      @billable_services_all.each do |bs|
        csv << bs.to_onetime_export_hash.values
      end
    end
  end


  def one_time_exports

    @search = BillableServiceExportSearch.new(onetime_search_params)
    @billable_services_all = @search.results.all
    @results_length = @billable_services_all.length
    @billable_services = @search.results.all.page params[:page]

    request.parameters.merge({:page => params[:page]})

    respond_to do |format|
      format.html
      format.json {         send_data self.to_csv, filename: "Onetime_Charges_#{onetime_search_params[:onetime_startdate]}_#{onetime_search_params[:onetime_enddate]}.csv" } # for some reason csv doesn't work....
    end

  end

  def exports
    @search = BillableServiceExportSearch.new(search_params)
    @billable_services_all = @search.results.all
    @results_length = @billable_services_all.length
    @billable_services = @search.results.all.page params[:page]

    request.parameters.merge({:page => params[:page]})

    puts @search.results.to_sql

    respond_to do |format|
      format.html
      format.json {         send_data self.to_csv, filename: "Charges_#{DateTime.now.strftime "%Y-%m-%d_%H%M"}.csv" } # for some reason csv doesn't work....
    end
  end

  def show
    respond_with(@billable_service)
  end

  def new
    @billable_service = BillableService.new
    respond_with(@billable_service)
  end

  def edit
  end

  def create
    @billable_service = BillableService.new(billable_service_params)
    if(@billable_service.recurrence_type == "One-time")
      @billable_service.deactivate!
    end
    @billable_service.save

    respond_with(@billable_service) and return unless request.referer
    if URI(request.referer).path == new_billable_service_path
      respond_with(@billable_service)
    else
      respond_with @billable_service, location: request.referer
    end
  end

  def update
    @billable_service.update(billable_service_params.except(:human_validation_date))
    respond_to do |format|
      format.html {
        if billable_service_params[:human_validation_date] =~ /\A1\z/
          @billable_service.human_validation_date = Time.now
          @billable_service.save!
        elsif billable_service_params[:human_validation_date] =~ /\A0\z/
          @billable_service.human_validation_date = nil
          @billable_service.save!
        end

        respond_with(@billable_service) and return unless request.referer
        if URI(request.referer).path == edit_billable_service_path(@billable_service)
          respond_with(@billable_service)
        else
          respond_with @billable_service, location: request.referer
        end
      }
      format.json {
        respond_with_bip(@billable_service) }
    end
  end

  def destroy
    @billable_service.destroy
    respond_with(@billable_service)
  end

  # Adds this BillableService to an invoice
  def add
    @billable_service = BillableService.new(billable_service_params)
    @client.add_billable_service(@btn, @invoice, @billable_service)

    respond_with(@billable_service) and return unless request.referer
    if URI(request.referer).path == edit_billable_service_path(@billable_service)
      respond_with(@billable_service)
    else
      respond_with @billable_service, location: request.referer
    end
  end

  # Removes this BillableService from an invoice
  def remove
    @client.remove_billable_service(@btn, @invoice, @billable_service)

    if URI(request.referer).path == edit_billable_service_path(@billable_service)
      respond_with(@billable_service)
    else
      respond_with @billable_service, location: request.referer
    end
  end

  private


    def set_billable_service
      @billable_service = BillableService.find(params[:id])
    end


    def set_client
      @client = Client.find(params[:client_id])
    end

    def set_btn
      @btn = Btn.find(params[:btn_id])
    end

    def set_invoice
      @invoice = Invoice.find(params[:invoice_id])
    end

    def billable_service_params
      if params[:billable_service][:product_id] == ''
        params[:billable_service][:product_id] = nil
      end
      params.require(:billable_service).permit(
        :client_id, :invoice_id, :product_id, :site_id, :qty, :service_begin, :service_end, :discount,
        :renewable, :comments, :total_price, :product_name, :asset_id, :foreign_pid,
        :unit_price, :frequency_months, :active_month, :renewal_id, :human_validation_date, :billing_period_started_at, :billing_period_ended_at, :unitprice, :billing_period, :charge_mode_id, :recurrence_type, :assignment_level, :prorate_id_start, :prorate_id_end, :reference_number, :supplier_account_no, :supplier_id, :password1, :note)



    end

    def has_client_id_param?
      params[:client_id].present?
    end

    def has_btn_id_param?
      params[:btn_id].present?
    end

    def has_invoice_id_param?
      params[:invoice_id].present?
    end

  protected

    def onetime_search_params
      if params.include?("billable_service_export_search")
        @search_params ||= params.delete(:billable_service_export_search) || {}
      else
        @search_params = {}
      end

      if not @search_params.include?("onetime_startdate")
        @search_params[:onetime_startdate] = Date.today.beginning_of_month
      end

      if @search_params[:onetime_startdate] == ""
        @search_params[:onetime_startdate] = Date.today.beginning_of_month
      end

      if not @search_params.include?("onetime_enddate")
        @search_params[:onetime_enddate] = Date.today.end_of_month
      end

      if @search_params[:onetime_enddate] == ""
        @search_params[:onetime_enddate] = Date.today.end_of_month
      end


      if not @search_params.include?("onetime")
        @search_params[:onetime] = true
      end

      @search_params

    end

    def search_params
      if params.include?("billable_service_search")
        @search_params ||= params.delete(:billable_service_search) || {}
      elsif params.include?("billable_service_export_search")
        @search_params ||= params.delete(:billable_service_export_search) || {}
      else
        @search_params = {}
      end

      if @client
        @search_params[:client] = @client.id
      end
      @search_params
    end

end

templates/jb_src/app/helpers/billable_services_helper.rb
module BillableServicesHelper
  # also used for phones.
  # I don't understand what this is for.  It just prints the site id in service listing --jlam 2018/05/16
  def service_site_selector(bs, choices)
    best_in_place bs, :site_id, place_holder: '-no-site-', as: :select, collection: choices
  end

  def change_current_url_type(page_format="html")
    ##########################################################################################
    # Change a url to have a specific extension while keeping the query params.
    #
    # This is to facilitate a work around where I (jjrh) was unable to request a specific page format
    # in the form.
    #
    # ex:
    #     <%= link_to "This page in CSV", change_current_url_type("json") %>
    #
    # from : billable_services/exports?..query..params..
    #
    # to   : billable_services/exports.json?..query..params..
    #
    # from : http://union:3000/clients/1357/billable_services/exports?utf8=%E2%9C%93&billable_service_export_search%...............
    # to   : http://union:3000/clients/1357/billable_services/exports.json?utf8=%E2%9C%93&billable_service_export_search%...............
    ##########################################################################################
    begin
      request.protocol+request.host_with_port+request.fullpath.split("?")[0]+".#{page_format}?"+request.fullpath.split("?")[1]
    rescue
      request.protocol+request.host_with_port+request.fullpath.split("?")[0]+".#{page_format}"
    end
  end


end

templates/jb_src/app/views/billable_services/_billable_services.html.erb
<%= render layout: 'shared/box', locals: { title: "Charges (#{@billable_services_count2})", extra_classes: "", id: "billable_services_widget" } do %>
  <div class="row">

  <div class="form-group">
    <div class="col-md-4">
      <% if deactivated_billable_services? %>
      <label class="control-label">Listing Deactivated Charges</label>
        <%= link_to 'Show Activated', client_show_safe_params.merge(deactivated_billable_services: 0), class: 'btn btn-default btn-box form-control' %>
      <% else %>
      <label class="control-label">Listing Activated Charges</label>
        <%= link_to 'Show Deactivated', client_show_safe_params.merge(deactivated_billable_services: 1), class: 'btn btn-default btn-box form-control' %>
      <% end %>
    </div>

    <%= render :file => 'shared/_site_picker.html.erb', :locals => {:ressourceName => 'billable'} %>

    <div class="col-md-4">
      <% if recurring_billable_services? %>
      <label class="control-label">Showing Recurring</label>
        <%= link_to 'Show One-Time', client_show_safe_params.merge(billable_service_recurrence: 1, deactivated_billable_services: 1), class: 'btn btn-default btn-box form-control' %>
      <% else %>
      <label class="control-label">Showing One-Time</label>
        <%= link_to 'Show Recurring', client_show_safe_params.merge(billable_service_recurrence: 2, deactivated_billable_services: 0), class: 'btn btn-default btn-box form-control' %>
      <% end %>
    </div>


    <div class="col-md-4">
    </div>
  </div>
  </div>
  <br>
  <div class="charges_scroll">

  <table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
	<th class="col-md-1">Service Status</th>
	<th class="col-md-1"></th>
        <th class="col-md-1">Service ID</th>
	<th class="col-md-1">Type</th>
        <th class="col-md-2">Description</th>
	<th class="col-md-1">Site</th>
        <th class="col-md-1">Quantity</th>
        <th class="col-md-1">Unit Price</th>
        <th class="col-md-1">Total</th>
        <th class="col-md-1">Start Date</th>
	<th class="col-md-1">End Date</th>


        <th class="col-md-1"></th>

      </tr>
    </thead>

    <tbody>
      <% @billable_services.each do |service| %>

        <tr>
          <td><%= service.activated? ? 'Active' : 'Inactive' %></td>
	  <td>
	    <small><table>
	      <tr><td>id:</td><td><%= service.id %></td></tr>
	      <tr><td>pid:</td><td><%= service.charge_pid %></td></tr>
	    </table></small>
	  </td>
	  <td>
	  <% if service.asset %>
	    <a href="/services/<%= service.asset.id %>"><%= service.asset.service_id %></a>
	      <!-- <br /><span style="overflow-x:hidden;" title="id:<%= service.asset.site_id %>" ><%= service_site_selector(service.asset, @selectable_site_collection) %></span> -->
	  <% end %>

	  </td>

	  <td><%= service.recurrence_type %></td>
          <td><b><%= service.name %></b><br>
	    <span title="product id:<%= service.product_id %>"><%= service.description %></span>
	  </td>
	  <td>
	    <% if service.site %>
	      <a href="/sites/<%= service.site.id %>">
	      <%= service.site.site_number %><br>
	      <%= service.site.name %>
		</a>
	    <% end %>
	    <%#= service.site != nil ? "#{service.site.site_number}" : '' %>

	  </td>
          <td><span class="pull-right"><%= service.qty %></span></td>
          <td><span class="pull-right"><%= money(service.unit_price) %></span></td>
          <td><span class="pull-right"><%= money(service.total) %></span></td>

          <td><%= date service.billing_period_started_at %></td>
          <td><%= date service.billing_period_ended_at %></td>

	  <td><%= link_to icon("edit"), edit_client_billable_service_path(@client,service), class: 'btn btn-warning btn-box btn-xs' %></td>


	  <% if nil %>
            <% servicePrice = Product.find_by(id: service.product_id).try(:unitprice) %>
	    <!-- <td><span class="pull-right"><%= money(service.product.unit_cost) if service.product  %></span></td> -->
            <!-- <td><span class="pull-right"><%= servicePrice.nil? ? 'n/d' : money(servicePrice) %></span></td> -->

            <% if service.activated? %>
              <td><%= link_to icon('minus'), client_billable_service_deactivate_path(@client, service), method: :patch, class: 'btn btn-danger btn-xs btn-box'%></td>
            <% else %>
              <td><%= link_to icon('plus'), client_billable_service_activate_path(@client, service), method: :patch, class: 'btn btn-success btn-xs btn-box'%></td>
            <% end %>
	  <% end %>



        </tr>
      <% end %>
    </tbody>

    <tfoot>
      <tr>
        <!-- <th colspan="6"><span class="pull-right">Total</span></th>
             <td><span class="pull-right"><%= money(@billable_services_total) %></span></td> -->
      </tr>
    </tfoot>
  </table>
  </div> <!-- end new div -->

  <% content_for :footer, flush: true do %>
    <%= link_to 'Add Charge', '#', class: "btn btn-xs btn-box btn-default", data: { toggle: 'modal', target: '#add-service-modal' } %>
    <%= link_to 'Search', client_billable_services_path(@client), class: "btn btn-xs btn-box btn-default" %>

    <%= paginate(@billable_services, param_name: :services_page) %>

    <%= render layout: 'shared/modal', locals: { title: 'Add Charge', html: { id: 'add-service-modal' }} do %>
      <%= render 'billable_services/form' %>
    <% end %>
  <% end %>
<% end %>

templates/jb_src/app/views/billable_services/edit.html.erb
<div class="box">
  <div class="box-header with-border">
    <h2 class="box-title"><strong>Editing service:</strong> <%= @billable_service.name %></h2>
    <div class="box-body">
      <i><%= @billable_service.description %></i>
    </div>
  </div>


  <!-- /.box-header -->
  <div class="box-body">
    <%= render 'form' %>
  </div>
  <!-- /.box-body -->

  <div class="box-footer clearfix">
    <%= link_to 'Show', billable_service_path %> |
    <%#= link_to 'Back', redirect_back_path || billable_services_path  %>
    <%= link_to 'Back', redirect_back_path  %>
  </div>
</div>
<!-- /.box -->

templates/jb_src/app/views/billable_services/index.html.erb
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Listing Services</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body">


    <%= form_for(@search, url: client_billable_services_path, method: :get, :html => {:class => ''}) do |f| %>

      <div class="row">
	<div class="col-md-4">
	  <%= f.collection_check_boxes :recurrences, BillableService.recurrence_types.map { |k,v| [k,v] }, :first, :first do |b| %>
	    <label class="checkbox-inline">
	      <%#= b.object[0] %>
	      <%#= b.label %>
	      <%= b.check_box %>
	      <%= b.object[0] %>
	    </label>
	  <% end %>
	</div>
      </div>  <!-- end row -->

      <div class="row" style="padding-top:4px">
	<div class="col-md-4">
	  <label class="checkbox-inline">
	    <%= f.check_box :activated %>
	    Activated
	  </label>
	  <label class="checkbox-inline">
	    <%= f.check_box :deactivated %>
	    Deactivated
	  </label>
	</div>
      </div>

      <div class="row search-group search-group-col">

	<div class="col-xs-3">
	  <div class=" input-group">
	    <span class="input-group-addon">Service ID:</span>
	    <%= f.text_field :assetid, class: 'form-control' %>
	  </div>
	</div>
	<div class="col-xs-3">
	  <div class="input-group">
	    <span class="input-group-addon">Product Code:</span>
	    <%= f.text_field :servicename, class: 'form-control' %>
	  </div>

	</div>
	<div class="col-xs-3">
	  <div class="input-group">
	    <span class="input-group-addon">Description:</span>
	    <%= f.text_field :servicedescription, class: 'form-control' %>

	  </div>
	</div>
	<div class="col-xs-3">
	  <div class="input-group">
	    <span class="input-group-addon" >Quantity:</span>
	    <%= f.text_field :quanity, class: 'form-control' %>
	  </div>
	</div>

	<% if false %>
	<div class="col-xs-3 " style="padding-left:0px;">
	  <div class="input-group">
	    <span class="input-group-addon">Code:</span>
	    <%= f.text_field :servicecode, class: 'form-control' %>
	  </div>
	</div>
	<% end %>
      </div> <!-- end row -->

      <div class="row search-group search-group-col" style="padding-top:4px">

	<div class="col-xs-3">
	  <div class="input-group">
	    <span class="input-group-addon" >Start Date:</span>
	    <%= f.text_field :startdate , class: 'form-control datepicker' %>
	  </div>
	</div>



	<div class="col-xs-3">
	  <div class="input-group">
	    <span class="input-group-addon" >End Date:</span>
	    <%= f.text_field :enddate , class: 'form-control datepicker' %>
	  </div>
	</div>


	<div class="col-xs-3" style="padding-left:0px;">
	  <!-- <div class="input-group"> -->
	  <div class="row">
	    <div class="col-xs-3" style="padding-right:0px">
	      <!-- <span class="input-group-addon selectize-input" style="padding-left:0px;" >Site:</span> -->
	    <span class="input-group-addon selectize-input" >Site:</span>
	    </div>
	    <!-- <div class="col-xs-9 selectize-custom" style="padding-left:0px"> -->
	    <div class="col-xs-9 selectize-custom" style="padding-left:0px">
	    <%= f.select :site, options_from_collection_for_select(@client.sites.sort_by { |s| s.site_number }, :id, lambda { |s| "#{s.site_number}, #{s.name}"}, @search.site), {:include_blank => true}, class: 'form-control ' %>
	    </div>
	  </div>
	</div>

      </div>  <!-- end row -->


      <script>
       $(document).ready(function(){
	 $("[name='billable_service_search[site]']").selectize({ create: true, sortField: 'text'});
       })
      </script>

      <div class="row" style="padding-top:4px">
	<div class="col-md-1">
	  <%= link_to 'reset', url_for(controller: 'billable_services', action: 'index', client_id: @client.id), class: "btn btn-warning" %>
	</div>

	<div class="col-md-1">
	  <%= f.submit "Search", class: 'btn btn-primary' %>
	</div>
      </div>

    <% end %>
    <hr>

    <% if @billable_services.length > 0 %>
      <table class="table table-bordered table-striped table-hover">
	<caption><b>Charges (<%= @results_length %>)</b></caption>
	<thead>
	  <tr>
	    <th class="col-md-1">Service Status</th>
	    <th class="col-md-1"></th>
            <th class="col-md-1">Service ID</th>
	    <th class="col-md-1">Type</th>
            <th class="col-md-2">Description</th>
	    <th class="col-md-1">Site</th>
            <th class="col-md-1">Quantity</th>
            <th class="col-md-1">Unit Price</th>
            <th class="col-md-1">Total</th>
            <th class="col-md-1">Start Date</th>
	    <th class="col-md-1">End Date</th>


            <th class="col-md-1"></th>

	  </tr>
	</thead>
	<tbody>
	  <% @billable_services.each do |service| %>
	    <tr>
	      <td><%= service.activated? ? 'Active' : 'Inactive' %></td>
	      <td>
		<small><table>
		  <tr><td>id:</td><td><%= service.id %></td></tr>
		  <tr><td>pid:</td><td><%= service.charge_pid %></td></tr>
		</table></small>
	      </td>
	      <td><% if service.asset %><a href="/services/<%= service.asset.id %>"><%= service.asset.service_id %></a><% end %></td>
	      <td><%= service.recurrence_type %></td>

	      <td><b><%= service.name %></b><br>
		<span title="product id:<%= service.product_id %>"><%= service.description %></span>
	      </td>

	      <td>
		<% if service.site %>
		  <a href="/sites/<%= service.site.id %>">
		    <%= service.site.site_number %><br>
		    <%= service.site.name %>
		  </a>
		<% end %>
	      </td>
              <td><span class="pull-right"><%= service.qty %></span></td>
              <td><span class="pull-right"><%= money(service.unit_price) %></span></td>
              <td><span class="pull-right"><%= money(service.total) %></span></td>

              <td><%= date service.billing_period_started_at %></td>
              <td><%= date service.billing_period_ended_at %></td>

	      <td><%= link_to icon("edit"), edit_client_billable_service_path(@client,service), class: 'btn btn-warning btn-box btn-xs' %></td>





	    </tr>
	  <% end %>
	</tbody>
      </table>
    <% end %>
    <% if false %>
  <table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <!-- <th class="col-md-1">Validation</th> -->
	<!-- <th>billable_service id</th> -->
	<th class="col-md-1"></th>
        <th class="col-md-2">Asset</th>
        <th class="col-md-1">Start Date</th>
        <th class="col-md-2">Name</th>
        <th class="col-md-4">Description</th>
        <th class="col-md-1"><span class="pull-right">Quantity</span></th>
        <th class="col-md-1"><span class="pull-right">Unit Price</span></th>
        <th class="col-md-1"><span class="pull-right">Service Price</span></th>
        <th class="col-md-1"><span class="pull-right">Total</span></th>
        <th class="col-md-1"></th>
        <th class="col-md-1"></th>
      </tr>
    </thead>
      <tbody>
        <% @billable_services.each do |service| %>
	  <tr>
	    <td><%= service.recurrence_type %></td>
          <td><% if service.asset %><%= service.asset.name %><% end %><%#= service.service_id %></td>
          <td><%= date service.billing_period_started_at %></td>
          <td><%= service.name %></td>
          <td><span title="<%= service.product_id %>"><%= service.description %></span></td>
          <td><span class="pull-right"><%= service.qty %></span></td>
          <td><span class="pull-right"><%= money(service.unit_price) %></span></td>
          <% servicePrice = Product.find_by(id: service.product_id).try(:unitprice) %>
          <td><span class="pull-right"><%= servicePrice.nil? ? 'n/d' : money(servicePrice) %></span></td>
          <td><span class="pull-right"><%= money(service.total) %></span></td>

          <!-- <td>
            <%# link_to icon("edit"), edit_billable_service_path(service), class: 'btn btn-warning btn-box btn-xs' %>
            <%# link_to icon("remove"), remove_billable_service_path(@client, @client.btn, @selected_invoice, service), class: 'btn btn-danger btn-box btn-xs', data: { confirm: "Terminate billable service.\n#{service.name} will be removed from this invoice.\nAre you sure?", method: :delete } %>
          </td> -->
          <% if service.activated? %>
            <td><%= link_to icon('minus'), client_billable_service_deactivate_path(@client, service), method: :patch, class: 'btn btn-danger btn-xs btn-box'%></td>
          <% else %>
            <td><%= link_to icon('plus'), client_billable_service_activate_path(@client, service), method: :patch, class: 'btn btn-success btn-xs btn-box'%></td>
          <% end %>

	  <td><%= link_to icon("edit"), edit_client_billable_service_path(@client,service), class: 'btn btn-warning btn-box btn-xs' %></td>


        </tr>
        <% end %>
      </tbody>
  </table>
  <% end %>
  </div>
  <!-- /.box-body -->

  <div class="box-footer clearfix">
    <%#= link_to 'New Service', new_service_path %>
    <% pathToNewBillableService = url_for(controller: 'billable_services', action: 'new', client_id: @client.id) %>
    <%= link_to 'Add Service', pathToNewBillableService, class: "btn btn-xs btn-box btn-default" %>




    <%= paginate @billable_services, params: request.parameters %>
  </div>
</div>
<!-- /.box -->

templates/jb_src/app/views/billable_services/new.html.erb
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">New service</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <%= render 'form' %>
  </div>
  <!-- /.box-body -->

  <div class="box-footer clearfix">
    <%= link_to 'Back', services_path %>
  </div>
</div>
<!-- /.box -->

templates/jb_src/app/views/billable_services/show.html.erb
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Editing service</h3>
  </div>
  <!-- /.box-header -->

  <div class="box-body">
    <p>
      <strong>Description:</strong>
      <%= @billable_service.description %>
    </p>

    <p>
      <strong>Name:</strong>
      <%= @billable_service.name %>
    </p>

    <p>
      <strong>Unitprice:</strong>
      <%= @billable_service.unitprice %>
    </p>

    <!-- <p>
	 <strong>Renewable:</strong>
	 <%#= @billable_service.renewable %>
	 </p> -->

    <!-- <p>
	 <strong>Available:</strong>
	 <%#= @billable_service.available %>
	 </p> -->
  </div>
  <!-- /.box-body -->

  <div class="box-footer clearfix">
    <%= link_to 'Edit', edit_billable_service_path(@billable_service) %> |
    <%= link_to 'Back', redirect_back_path || billable_services_path %>
  </div>
</div>
<!-- /.box -->