templates/jb_src/config/routes.rb
Rails.application.routes.draw do

  resources :inventories
  get 'inventories/:id/mod_new', to: 'inventories#mod_new', as: :mod_new_inventory

  resources :contacts, only: [:index]

  resources :payments
  root 'root#index'

  post 'reset', to: 'query#reset'
  post 'clients_reset', to: 'clients#reset'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  post '/search', to: 'searches#create'
  get '/search', to: 'searches#show', as: :show_search

  resources :dashboards, only: [:index] do
    collection do
      get 'payment/process', to: 'dashboards#process_payment'
    end
  end

  concern :activatable do
    patch :activate
    patch :deactivate
  end


  resources :billable_services, concerns: :activatable do
    collection do
      get '/exports', to: 'billable_services#exports'
      get '/onetime', to: 'billable_services#one_time_exports'
    end
  end


  resources :settings
  resources :contacts
  resources :payments
  # resources :rates
  # resources :services
  resources :billable_services
  # resources :stats_periods
  # resources :performance_stats
  # resources :local_exchanges
  # resources :local_exchanges_north_american_exchanges
  # resources :north_american_exchanges
  # resources :rate_centers
  # resources :calls
  # resources :products, only: [:index, :show, :edit, :update, :new ]
  resources :products
  resources :invoices, only: [:index, :show]

  resources :clients do
    resource :billing, only: [:edit, :update]

    #resources :contacts, only: [:index, :phone_contact_create]
    #resources :contacts, concerns: :activatable

    resources :contacts do

      collection do
        resources :phone_contacts#, :only => [:new, :edit, :destroy]
        resources :email_contacts#, :only => [:new, :edit, :destroy]
        # resources :technical_contacts, :only => [:new, :edit, :destory]
        resources :technical_contacts
      end

    end
    resources :billable_services, concerns: :activatable, :only => [:new, :edit, :index]
    resources :invoices, only: [:index, :show]

    resources :payments

    collection do
      get 'typeahead', constraints: { format: 'json' }
    end

    resources :sites, concerns: :activatable

    # resources :calls do
    #   resources :cdrs
    # end

    # resources :incoming_cdrs, :controller => "cdrs"
    #
    # resources :outgoing_cdrs, :controller => "cdrs"

    # resources :btns do
    #
    #   resources :phones
    #
    #   get '/invoices', to: 'invoices#index'
    #   get '/invoices/:year/:month', to: 'invoices#show'
    #
    #   resources :calls
    # end

    resources :services, concerns: :activatable
    # resources :billable_services, concerns: :activatable
    resources :sites, concerns: :activatable
    resources :buildings
    # resources :callstats
    #
    # resources :stats_periods do
    #   resources :callstats
    # end
  end

  # resources :services do
  #   resources :client_services
  # end

  # resources :client_services

  resources :btns do
    collection do
      get 'typeahead', constraints: { format: 'json' }
    end

    # resources :calls
  end

  # resources :datasources do
  #   resources :calls
  #   resources :cdrs do
  #     resources :calls
  #   end
  # end

  resources :sites, concerns: :activatable

  resources :buildings

  resources :services, concerns: :activatable, path_names: { new: 'new/client/:client_id'}

  # resources :callingphones, :controller => "phones" do
  #   resources :cdrs
  # end
  #
  # resources :calledphones, :controller => "phones" do
  #   resources :cdrs
  # end

  # resources :cdrs do
  # end

  namespace :admin do
    resources :users
  end

  resources :client_line_of_businesses, only: [:update]

  namespace :api, defaults: { format: 'json' } do
      namespace :v1, constraints: { format: 'json' } do
        resources :btns, only: [], param: 'slug' do
          resources :services, only: [:index, :show], param: 'slug'
        end
      end
  end

end

templates/jb_src/app/models/hakka/product.rb
module Hakka
  class Product < HakkaRecord
    # In March 2018, Services has been renamed to product as part of t13330.  The code here has not be touched as part of this effort as I don't believe it is in use.  -- jlam@credil.org

    self.primary_key = "ProductPID"
    self.table_name  = "Product"

    has_one :service,
      class_name: '::Service',
      foreign_key: 'foreign_pid'

    has_many :customers,
      through: :charge_assignments

    has_many :departments,
      through: :charge_assignments

    has_many :charge_assignments,
             foreign_key: 'ProductPID'

    belongs_to :product_category, foreign_key: 'ProductCategoryPID'

    def make_service_hash
      { name: self[:Code],
        foreign_pid: self[:ProductPID],
        description: self[:Description],
        unitprice: self[:UnitCost] || self[:Amount],
        renewable: true,
        available: self[:Active]
      }
    end

    def make_product
      ::Service.create(make_service_hash)
    end

    def map_by_foreign_pid
      n = ::Service.where(foreign_pid: self[:ProductPID]).take
      n.update(make_service_hash) if n
      n
    end

    def associated_service
      map_by_foreign_pid || make_product
    end


    def make_service_hash
      { name: self[:Code],
        foreign_pid: self[:ProductPID],
        description: self[:Description],
        unitprice: self[:UnitCost],
        renewable: true,
        available: self[:Active]
      }
    end

  end
end

templates/jb_src/app/models/hakku/product.rb
#
# this maps to the "Service" model
# # In March 2018, the Service model was renamed Product.  This code here was not touched as part of that rename effort as I don't thihk this code has been in use
#

module Hakku
  class Product < HakkuRecord

    self.primary_key = "ProductPID"
    self.table_name  = "Product"

    has_one :service,
      class_name: '::Service',
      foreign_key: 'foreign_pid'

    has_many :customers,
      through: :charge_assignments

    has_many :departments,
      through: :charge_assignments

    has_many :charge_assignments,
             foreign_key: 'ProductPID'

    belongs_to :product_category, foreign_key: 'ProductCategoryPID'

    def make_service_hash
      { name: self[:Code],
        foreign_pid: self[:ProductPID],
        description: self[:Description],
        unitprice: self[:UnitCost] || self[:Amount],
        renewable: true,
        available: self[:Active]
      }
    end

    def make_product
      ::Service.create(make_service_hash)
      $HAKKUSTATS[:product_created] += 1
    end

    def map_by_foreign_pid
      n = ::Service.where(foreign_pid: self[:ProductPID]).take
      if n
        n.update(make_service_hash)
        $HAKKUSTATS[:product_reused] += 1
      end
      n
    end

    def associated_service
      map_by_foreign_pid || make_product
    end


    def make_service_hash
      { name: self[:Code],
        foreign_pid: self[:ProductPID],
        description: self[:Description],
        unitprice: self[:UnitCost],
        renewable: true,
        available: self[:Active]
      }
    end

    def self.import_row(row)
      while (row[3] != '0' and row[3] != '1') or row[3] == nil
        #byebug if !row[2] or !row[3]
        row3 = row[3] || ""
        row[2] = row[2] + ',' + row3
        row.delete_at(3)
      end
      item = create!( ProductPID: row[0],
                      Code: row[1],
                      Description: row[2],
                      Amount: row[5],
                      UnitCost: row[20])
      item
    end

    def self.import_file(filename, encoding = 'CP863:UTF-8')
      cnt = 0
      CSV.foreach filename, headers: :first_row, encoding: encoding do |row|
        begin
          row2 = []
          row.each_entry {|n| row2 << n[1] }
          item = self.import_row(row2)
          cnt += 1
        rescue CSV::MalformedCSVError => e # Encoding::UndefinedConversionError, RangeError => e
          Rails.logger.error e.message
        end
      end
      return cnt
    end

  end
end

templates/jb_src/app/models/product.rb
class Product < ApplicationRecord

  paginates_per 18

  has_many :billable_services

  # Hakka
  belongs_to :hakka_product, :class_name => 'Hakka::Product', :foreign_key => 'foreign_pid' if $CONNECTMSSQL


  belongs_to :product_class
  belongs_to :product_category
  belongs_to :product_type
  belongs_to :line_of_business
  belongs_to :gl_account

  def update_from_hakka
    hp = self.hakka_product
    self.update(hp.make_service_hash)
  end


  IMPORT_MAPPING = {
        product_pid: "ProductPID",
        code: "Code",
        name: "Name",
        description: "Description",
        active: "Active",
        multi_jurisdictional_taxing: "MultiJurisdictionalTaxing",
        amount: "Amount",
        unit_cost: "UnitCost",
        purchase_amount: "PurchaseAmount",
        product_class: "ProductClassPID",
        product_category: "ProductCategoryPID",
        product_type: "ProductTypePID",
        line_of_business: "LineOfBusinessPID"   ,
        tax_passthrough: "TaxPassthrough"  ,
        gl_account: "GLAccountPID"    ,
        allow_fractional_qty: "AllowFractionalQuantity" ,
        pp_product_pid: "PPProductPID"    ,
        bc_product_pid: "BCProductPID",

      }
    IMPORT_PRIMARY_KEY = :product_pid

  def self.update_from_products_csv(filePath)
    self.update_from_csv(filePath, self::IMPORT_MAPPING, self::IMPORT_PRIMARY_KEY)
  end

  class ANI < Product
  end

  class Dedicated < Product
  end

  class Travel < Product
  end

  class TollFreeSwitchedAndDedicated < Product
  end

  class VirtualDID < Product
  end

end

templates/jb_src/app/models/product_type.rb
class ProductType < ApplicationRecord
    IMPORT_MAPPING = {
        :name               => "Code",
        :product_type_pid    => "ProductTypePID"
    }

    IMPORT_PRIMARY_KEY = :product_type_pid
end

templates/jb_src/app/controllers/products_controller.rb
class ProductsController < AuthorizationController
  include Search::ControllerHelpers

  layout 'admin_lte'

  before_action :set_product, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def index
    # @products = Product.all #.page params[:page]
    # @products = Product.includes(:line_of_business).order("line_of_business.code DESC")
    @products = Product.includes(:line_of_business).order(:code)

    respond_with(@products)
  end

  def show
    respond_with(@product)
  end

  def new
    @product = Product.new
    respond_with(@product)
  end

  def edit
    @dependent_bs = BillableService.where(:product => @product)
    respond_with(@product, @dependent_bs)
  end

  def create
    @product = Product.new(product_params)
    @product.save
    respond_with(@product)
  end

  def update
    @product.update(product_params)
    respond_with(@product)
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:description, :name, :unitprice, :renewable, :available, :code, :amount, :purchase_amount, :product_category_id, :product_class_id, :product_type_id, :gl_account_id, :line_of_business_id)
    end

end

templates/jb_src/app/helpers/products_helper.rb
module ProductsHelper
end

templates/jb_src/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <label class="col-sm-2 control-label">Name:</label>
    <div class="col-sm-10">
      <%= f.text_field :name,class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Code:</label>
    <div class="col-sm-10">
      <%= f.text_field :code,class: 'form-control' %>
    </div>
  </div>



  <div class="form-group">
    <label class="col-sm-2 control-label">Description:</label>
    <div class="col-sm-10">
      <%= f.text_field :description, class: 'form-control' %>
    </div>
  </div>


  <div class="form-group">
    <label class="col-sm-2 control-label">Amount:</label>
    <div class="col-sm-10">
      <%= f.text_field :amount, class: 'form-control' %>
    </div>
  </div>


  <div class="form-group">
    <label class="col-sm-2 control-label">Purchase Amount:</label>
    <div class="col-sm-10">
      <%= f.text_field :purchase_amount, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Product Category:</label>
    <div class="col-sm-10">
      <%= f.select :product_category_id, options_from_collection_for_select(ProductCategory.all, :id, :product_category_label, @product.product_category_id), {}, class: ' form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Product Class:</label>
    <div class="col-sm-10">
      <%= f.select :product_class_id, options_from_collection_for_select(ProductClass.all, :id, :product_class_label, @product.product_class_id), {}, class: ' form-control' %>
    </div>
  </div>

  <div type="form-group">
    <label class="col-sm-2 control-label">Product Type:</label>
    <div class="col-sm-10">
      <%= f.select :product_type_id, options_from_collection_for_select(ProductType.all, :id, :name, @product.product_type_id), {}, class: ' form-control' %>
    </div>
  </div>


  <div type="form-group">
    <label class="col-sm-2 control-label">GL Account:</label>
    <div class="col-sm-10">
      <%= f.select :gl_account_id, options_from_collection_for_select(GlAccount.all, :id, :gl_account_label, @product.gl_account_id), {}, class: ' form-control' %>
    </div>
  </div>


  <div type="form-group">
    <label class="col-sm-2 control-label">Line of Business:</label>
    <div class="col-sm-10">
      <%= f.select :line_of_business_id, options_from_collection_for_select(LineOfBusiness.all, :id, :code, @product.line_of_business_id), {}, class: ' form-control' %>
    </div>
  </div>



  <div class="actions">
    <%#= f.submit %>
    <%= f.submit nil, class: 'btn btn-primary btn-box' %>
  </div>
<% end %>

<% if @dependent_bs %>
<hr>
<button id="show_dependent_table" class="btn btn-info btn-sm">show</button> <b> Effected Charges: <%= @dependent_bs.length %></b>
<div id="dependent_charges" style="display:none">
  <table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
	<th>ID</th>
	<th>Client Name</th>
	<th>Site Name</th>
	<th>Site Number</th>
	<th></th>
      </tr>
    </thead>
    <tbody>
      <% @dependent_bs.each do |bs| %>
	<tr>
	  <td><%= bs.id %></td>
	  <td><%= bs.client.name %></td>
	  <td><%= bs.site.name %></td>
	  <td><%= bs.site.site_number %></td>
	  <td><%= link_to icon("edit"), edit_client_billable_service_path(bs.client.id,bs), class: 'btn btn-warning btn-box btn-xs' %></td>
	</tr>
      <% end %>
    </tbody>
  </table>
</div>
<script>$("#show_dependent_table").click(function(){
   if($("#dependent_charges").is(":visible")){ $("#dependent_charges").hide(); $("#show_dependent_table").text("show"); }
   else { $("#dependent_charges").show(); $("#show_dependent_table").text("hide"); }
  })
</script>
<% end %>

templates/jb_src/app/views/products/_products.html.erb
<%= render layout: 'shared/box', locals: { title: "#{icon 'service'} Services".html_safe, footer: nil } do %>
  <%= render 'searches/form' %>

  <!-- NOTE: It's empty because I can't realistically get this feature in for tomorrow -->
  <table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Unitprice</th>
        <th>Renewable</th>
        <th>Available</th>
      </tr>
    </thead>

    <tbody>
      <tr>
      </tr>
    </tbody>
  </table>
<% end %>

templates/jb_src/app/views/products/edit.html.erb
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Editing service</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <%= render 'form' %>
  </div>
  <!-- /.box-body -->

  <div class="box-footer clearfix">
    <%= link_to 'Show', @service %> |
    <%= link_to 'Back', services_path %>
  </div>
</div>
<!-- /.box -->

templates/jb_src/app/views/products/index.html.erb
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Listing Products</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <%#= render 'searches/form' %>

    <table class="table table-bordered table-striped table-hover">
      <thead>
        <tr>
	  <!-- <th>ID</th> -->
          <th>Name</th>
          <th>Description</th>
	  <th>Line of Business</th>

          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <tr>
	    <!-- <td><%#= product.id %></td> -->
            <td><%= product.name %></td>
            <td><%= product.description %></td>
	    <td><% if product.line_of_business %><%= product.line_of_business.code %><% end %></td>
	    <!-- <td><%#= product.code %></td> -->
            <td>
	      <%#= link_to 'Show', product %>
              <%= link_to icon("edit"), edit_product_path(product), class: 'btn btn-warning btn-box btn-xs' %>
              <%#= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
	    </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <!-- /.box-body -->

  <div class="box-footer clearfix">
    <%= link_to 'New Product', new_product_path, class: "btn btn-xs btn-box btn-default" %>
    <%#= paginate @products %>
  </div>
</div>
<!-- /.box -->

templates/jb_src/app/views/products/new.html.erb
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">New service</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <%= render 'form' %>
  </div>
  <!-- /.box-body -->

  <div class="box-footer clearfix">
    <%= link_to 'Back', services_path %>
  </div>
</div>
<!-- /.box -->

templates/jb_src/app/views/products/show.html.erb
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">Editing product</h3>
  </div>
  <!-- /.box-header -->

  <div class="box-body">
    <p>
      <strong>Description:</strong>
      <%= @product.description %>
    </p>

    <p>
      <strong>Name:</strong>
      <%= @product.name %>
    </p>

    <p>
      <strong>Unitprice:</strong>
      <%#= @product.unitprice %>
    </p>

    <p>
      <strong>Renewable:</strong>
      <%= @product.renewable %>
    </p>

    <p>
      <strong>Available:</strong>
      <%#= @product.available %>
    </p>
  </div>
  <!-- /.box-body -->

  <div class="box-footer clearfix">
    <%#= link_to 'Edit', edit_product_path(@product) %> |
    <%= link_to 'Back', products_path %>
  </div>
</div>
<!-- /.box -->