templates/jb_src/config/routes.rb
Rails.application.routes.draw do

  resources :inventories
  get 'inventories/:id/mod_new', to: 'inventories#mod_new', as: :mod_new_inventory

  resources :contacts, only: [:index]

  resources :payments
  root 'root#index'

  post 'reset', to: 'query#reset'
  post 'clients_reset', to: 'clients#reset'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  post '/search', to: 'searches#create'
  get '/search', to: 'searches#show', as: :show_search

  resources :dashboards, only: [:index] do
    collection do
      get 'payment/process', to: 'dashboards#process_payment'
    end
  end

  concern :activatable do
    patch :activate
    patch :deactivate
  end


  resources :billable_services, concerns: :activatable do
    collection do
      get '/exports', to: 'billable_services#exports'
      get '/onetime', to: 'billable_services#one_time_exports'
    end
  end


  resources :settings
  resources :contacts
  resources :payments
  # resources :rates
  # resources :services
  resources :billable_services
  # resources :stats_periods
  # resources :performance_stats
  # resources :local_exchanges
  # resources :local_exchanges_north_american_exchanges
  # resources :north_american_exchanges
  # resources :rate_centers
  # resources :calls
  # resources :products, only: [:index, :show, :edit, :update, :new ]
  resources :products
  resources :invoices, only: [:index, :show]

  resources :clients do
    resource :billing, only: [:edit, :update]

    #resources :contacts, only: [:index, :phone_contact_create]
    #resources :contacts, concerns: :activatable

    resources :contacts do

      collection do
        resources :phone_contacts#, :only => [:new, :edit, :destroy]
        resources :email_contacts#, :only => [:new, :edit, :destroy]
        # resources :technical_contacts, :only => [:new, :edit, :destory]
        resources :technical_contacts
      end

    end
    resources :billable_services, concerns: :activatable, :only => [:new, :edit, :index]
    resources :invoices, only: [:index, :show]

    resources :payments

    collection do
      get 'typeahead', constraints: { format: 'json' }
    end

    resources :sites, concerns: :activatable

    # resources :calls do
    #   resources :cdrs
    # end

    # resources :incoming_cdrs, :controller => "cdrs"
    #
    # resources :outgoing_cdrs, :controller => "cdrs"

    # resources :btns do
    #
    #   resources :phones
    #
    #   get '/invoices', to: 'invoices#index'
    #   get '/invoices/:year/:month', to: 'invoices#show'
    #
    #   resources :calls
    # end

    resources :services, concerns: :activatable
    # resources :billable_services, concerns: :activatable
    resources :sites, concerns: :activatable
    resources :buildings
    # resources :callstats
    #
    # resources :stats_periods do
    #   resources :callstats
    # end
  end

  # resources :services do
  #   resources :client_services
  # end

  # resources :client_services

  resources :btns do
    collection do
      get 'typeahead', constraints: { format: 'json' }
    end

    # resources :calls
  end

  # resources :datasources do
  #   resources :calls
  #   resources :cdrs do
  #     resources :calls
  #   end
  # end

  resources :sites, concerns: :activatable

  resources :buildings

  resources :services, concerns: :activatable, path_names: { new: 'new/client/:client_id'}

  # resources :callingphones, :controller => "phones" do
  #   resources :cdrs
  # end
  #
  # resources :calledphones, :controller => "phones" do
  #   resources :cdrs
  # end

  # resources :cdrs do
  # end

  namespace :admin do
    resources :users
  end

  resources :client_line_of_businesses, only: [:update]

  namespace :api, defaults: { format: 'json' } do
      namespace :v1, constraints: { format: 'json' } do
        resources :btns, only: [], param: 'slug' do
          resources :services, only: [:index, :show], param: 'slug'
        end
      end
  end

end

templates/jb_src/app/models/contact.rb
class Contact
end

templates/jb_src/app/controllers/contacts_controller.rb
class ContactsController < AuthorizationController

  layout 'admin_lte'

  before_action :set_contacts, only: [:index]

  respond_to :html

  def index
    if @client
      respond_with(@client, @phone_contacts, @email_contacts, @technical_contacts)
    else
      respond_with(@phone_contacts, @email_contacts, @technical_contacts)
    end
  end

  private

    def set_contacts
      if @client
        @phone_contacts = @client.phone_contacts
        @email_contacts = @client.email_contacts
        @technical_contacts = @client.technical_contacts
      else
        @phone_contacts = PhoneContact.all
        @email_contacts = EmailContact.all
        @technical_contacts = TechnicalContact.all
      end
    end

end

templates/jb_src/app/helpers/contacts_helper.rb
module ContactsHelper
end

templates/jb_src/app/views/contacts/_form.html.erb
<% if @client %>
  <%= form_for([@client, @contact]) do |f| %>
    <%= render 'contacts/form/fields', f: f %>
  <% end %>
<% else %>
  <%= form_for(@contact) do |f| %>
    <%= render 'contacts/form/fields', f: f %>
  <% end %>
<% end %>

templates/jb_src/app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<% if @client %>
  <%= link_to 'Show', client_contact_path(@client, @contact) %> |
  <%= link_to 'Back', client_contacts_path(@client) %>
<% else %>
  <%= link_to 'Show', @contact %> |
  <%= link_to 'Back', contacts_path %>
<% end %>

templates/jb_src/app/views/contacts/index.html.erb
<% content_for :title do %>
  Listing Contacts
<% end -%>

<div class="row">
  <div class="col-md-12">
    <%= render layout: 'shared/box', locals: { title: "#{icon(icon_for 'contact')} Phone Contacts".html_safe } do %>
      <table class="table table-bordered table-striped table-hover">
        <thead>
          <tr>
            <th class="col-md-3">Phone Type</th>
            <th class="col-md-3">Phone Number</th>
            <th class="col-md-4">Name</th>
            <th class="col-md-3"></th>
          </tr>
        </thead>

        <tbody>
          <% @phone_contacts.each do |contact| %>
            <tr>
              <td><%= contact.phone_type %></td>
              <td><%= contact.phone_number %></td>
              <td><%= contact.name %></td>
              <td>
		<%= link_to edit_client_phone_contact_path(@client,contact), class: "btn btn-warning btn-sm", title: "Edit" do %>
		  <i class="fa fa-pencil-square-o"></i> Edit
		  <% end %>
		<%= link_to client_phone_contact_path(@client,contact), class: "btn btn-danger btn-sm", title: "Delete", method: :delete, data: { confirm: 'Are you sure?' } do %>
		  <i class="fa fa-trash-o"></i> Delete
		<% end %>
	      </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div style="margin-left:10px; margin-top:16px;">
	<%= link_to new_client_phone_contact_path(@client), class: "btn btn-success btn-sm" do %>
	  <i class="fa fa-plus fa-lg"></i> New
	<% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= render layout: 'shared/box', locals: { title: "#{icon(icon_for 'contact')} Email Contacts".html_safe } do %>
      <table class="table table-bordered table-striped table-hover">
        <thead>
          <tr>
            <th class="col-md-3">Email</th>
            <th class="col-md-3">Name</th>
            <th class="col-md-3">Email Type</th>
            <th class="col-md-1">Subscribed</th>
            <th class="col-md-3"></th>
          </tr>
        </thead>

        <tbody>
          <% @email_contacts.each do |contact| %>
            <tr>
              <td><%= contact.email %></td>
              <td><%= contact.name %></td>
              <td><%= contact.email_type %></td>
	      <td><% if contact.subscribed %><i class="fa fa-lg fa-check-circle-o text-success"></i><% else %><i class="fa fa-lg fa-times-circle-o text-danger"></i><% end %> </td>
              <td>
		<%= link_to edit_client_email_contact_path(@client,contact), class: "btn btn-warning btn-sm", title: "Edit" do %>
		  <i class="fa fa-pencil-square-o"></i> Edit
		<% end %>
		<%= link_to client_email_contact_path(@client,contact), class: "btn btn-danger btn-sm", title: "Delete",  method: :delete, data: { confirm: 'Are you sure?' } do %>
		  <i class="fa fa-trash-o"></i> Delete
		<% end %>
	      </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div style="margin-left:10px; margin-top:16px;">
	<%= link_to new_client_email_contact_path(@client), class: "btn btn-success btn-sm" do %>
	  	<i class="fa fa-plus fa-lg"></i> New
	<% end %>
      </div>

      <%#= form_for(:EmailContact, :html => {:class => 'form-inline'}) do |f| %>
	<%#= render 'contacts/EmailContact', f: f %>
      <%# end %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= render layout: 'shared/box', locals: { title: "#{icon(icon_for 'contact')} Technical Contacts".html_safe } do %>
      <table class="table table-bordered table-striped table-hover">
        <thead>
          <tr>
            <th class="col-md-3">Name</th>
            <th class="col-md-3">Department</th>
            <th class="col-md-4">Email</th>
            <th class="col-md-3"></th>
          </tr>
        </thead>

        <tbody>
          <% @technical_contacts.each do |contact| %>
            <tr>
              <td><%= contact.name %></td>
              <td><%= contact.department %></td>
              <td><%= contact.email %></td>
              <td>
		<%= link_to edit_client_technical_contact_path(@client,contact), class: "btn btn-warning btn-sm", title: "Edit" do %>
		  <i class="fa fa-edit"></i> Edit
		<% end %>
		<%= link_to client_technical_contact_path(@client,contact), class: "btn btn-danger btn-sm ", title: "Delete", method: :delete, data: { confirm: 'Are you sure?' } do %>
		  <i class="fa fa-trash-o"></i> Delete
		<% end %>
	      </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div style="margin-left:10px; margin-top:16px;">
      <%= link_to new_client_technical_contact_path(@client), class: "btn btn-success btn-sm" do %>
	<i class="fa fa-plus fa-lg"></i> New
      <% end %>
      </div>
      <%#= form_for [Client, @TechnicalContact ] do |f| %>
      <%#= form_for (:technical_contact) do |f| %>

	<%#= f.text_field :email, class: 'form-control' %>
	<%#= f.text_field :name, class: 'form-control' %>
	<%#= f.text_field :department, class: 'form-control' %>
	<%#= f.submit %>
      <%# end %>
      <%#= link_to 'Destroy', destroy_client_technical_contact(@client) %>

      <%#= link_to 'Destroy', destroy_client_technical_contact, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= link_to 'Back', redirect_back_path || clients_path, class: 'btn btn-default btn-box' %>
  </div>
</div>

templates/jb_src/app/views/contacts/new.html.erb
<% content_for :title do %>
  New Contact
<% end -%>

<div class="row">
  <div class="col-md-4">
    <%= render layout: 'shared/box', locals: { title: "#{icon(icon_for 'contact')} New Contact".html_safe } do %>
      <%= render 'form' %>
    <% end %>
  </div>
</div>

templates/jb_src/app/views/contacts/show.html.erb
<% content_for :title do %>
  Contact
<% end -%>

<div class="row">
  <div class="col-md-4">
    <%= render layout: 'shared/box', locals: { title: "#{icon(icon_for 'contact')} Contact".html_safe } do %>
      <p>
        <strong>Email:</strong>
        <%= @contact.email %>
      </p>

      <p>
        <strong>Name:</strong>
        <%= @contact.name %>
      </p>

      <p>
        <strong>Role:</strong>
        <%= @contact.role %>
      </p>

      <p>
        <strong>Phone number:</strong>
        <%= @contact.phone_number %>
      </p>

      <p>
        <strong>Active:</strong>
        <%= @contact.active %>
      </p>

      <% if @client %>
        <%= link_to 'Edit', edit_client_contact_path(@client, @contact) %> |
        <%= link_to 'Back', client_contacts_path(@client) %>
      <% else %>
        <%= link_to 'Edit', edit_contact_path(@contact) %> |
        <%= link_to 'Back', contacts_path %>
      <% end %>
    <% end %>
  </div>
</div>