templates/jb_src/config/routes.rb
Rails.application.routes.draw do

  resources :inventories
  get 'inventories/:id/mod_new', to: 'inventories#mod_new', as: :mod_new_inventory

  resources :contacts, only: [:index]

  resources :payments
  root 'root#index'

  post 'reset', to: 'query#reset'
  post 'clients_reset', to: 'clients#reset'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  post '/search', to: 'searches#create'
  get '/search', to: 'searches#show', as: :show_search

  resources :dashboards, only: [:index] do
    collection do
      get 'payment/process', to: 'dashboards#process_payment'
    end
  end

  concern :activatable do
    patch :activate
    patch :deactivate
  end


  resources :billable_services, concerns: :activatable do
    collection do
      get '/exports', to: 'billable_services#exports'
      get '/onetime', to: 'billable_services#one_time_exports'
    end
  end


  resources :settings
  resources :contacts
  resources :payments
  # resources :rates
  # resources :services
  resources :billable_services
  # resources :stats_periods
  # resources :performance_stats
  # resources :local_exchanges
  # resources :local_exchanges_north_american_exchanges
  # resources :north_american_exchanges
  # resources :rate_centers
  # resources :calls
  # resources :products, only: [:index, :show, :edit, :update, :new ]
  resources :products
  resources :invoices, only: [:index, :show]

  resources :clients do
    resource :billing, only: [:edit, :update]

    #resources :contacts, only: [:index, :phone_contact_create]
    #resources :contacts, concerns: :activatable

    resources :contacts do

      collection do
        resources :phone_contacts#, :only => [:new, :edit, :destroy]
        resources :email_contacts#, :only => [:new, :edit, :destroy]
        # resources :technical_contacts, :only => [:new, :edit, :destory]
        resources :technical_contacts
      end

    end
    resources :billable_services, concerns: :activatable, :only => [:new, :edit, :index]
    resources :invoices, only: [:index, :show]

    resources :payments

    collection do
      get 'typeahead', constraints: { format: 'json' }
    end

    resources :sites, concerns: :activatable

    # resources :calls do
    #   resources :cdrs
    # end

    # resources :incoming_cdrs, :controller => "cdrs"
    #
    # resources :outgoing_cdrs, :controller => "cdrs"

    # resources :btns do
    #
    #   resources :phones
    #
    #   get '/invoices', to: 'invoices#index'
    #   get '/invoices/:year/:month', to: 'invoices#show'
    #
    #   resources :calls
    # end

    resources :services, concerns: :activatable
    # resources :billable_services, concerns: :activatable
    resources :sites, concerns: :activatable
    resources :buildings
    # resources :callstats
    #
    # resources :stats_periods do
    #   resources :callstats
    # end
  end

  # resources :services do
  #   resources :client_services
  # end

  # resources :client_services

  resources :btns do
    collection do
      get 'typeahead', constraints: { format: 'json' }
    end

    # resources :calls
  end

  # resources :datasources do
  #   resources :calls
  #   resources :cdrs do
  #     resources :calls
  #   end
  # end

  resources :sites, concerns: :activatable

  resources :buildings

  resources :services, concerns: :activatable, path_names: { new: 'new/client/:client_id'}

  # resources :callingphones, :controller => "phones" do
  #   resources :cdrs
  # end
  #
  # resources :calledphones, :controller => "phones" do
  #   resources :cdrs
  # end

  # resources :cdrs do
  # end

  namespace :admin do
    resources :users
  end

  resources :client_line_of_businesses, only: [:update]

  namespace :api, defaults: { format: 'json' } do
      namespace :v1, constraints: { format: 'json' } do
        resources :btns, only: [], param: 'slug' do
          resources :services, only: [:index, :show], param: 'slug'
        end
      end
  end

end

templates/jb_src/app/models/dashboard.rb
class Dashboard
end

templates/jb_src/app/controllers/dashboards_controller.rb
class DashboardsController < AuthorizationController
  include Search::ControllerHelpers

  layout 'admin_lte'

  before_action :set_client, :set_selectable_invoices, only: [:process_payment, :exports]

  def index
    @customers_count = Client.activated.count
    @btns_count = Btn.activated.count
    @sites_count = Site.activated.count
    @phones_count = Service.activated.count
  end

  def process_payment
    @payment = Payment.new(client: @client)

  end

  private

    def set_selectable_invoices
      @selectable_invoices = @client.invoices
    end

    def set_client
      @client = Client.find(params[:client_id])
    end

end

templates/jb_src/app/helpers/dashboards_helper.rb
module DashboardsHelper
end

templates/jb_src/app/views/dashboards/index.html.erb
<% if can? :manage, :any %>
  <!-- Info boxes -->
  <div class="row">

    <% # Only displays the clients count box if the user has access %>
    <% if can? :read, Client %>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
          <span class="info-box-icon bg-aqua"><i class="fa fa-user"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Customers</span>
            <span class="info-box-number"><%= @customers_count %></span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
    <% end %>

    <% # Only displays the btns count box if the user has access %>
    <% if can? :read, Btn %>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
          <span class="info-box-icon bg-red"><i class="fa fa-phone"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Btns</span>
            <span class="info-box-number"><%= @btns_count %></span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
    <% end %>

    <!-- fix for small devices only -->
    <div class="clearfix visible-sm-block"></div>

    <% # Only displays the sites count box if the user has access %>
    <% if can? :read, Site %>
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
          <span class="info-box-icon bg-green"><i class="fa fa-building"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Sites</span>
            <span class="info-box-number"><%= @sites_count %></span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
    <% end %>

    <% # Only displays the phones count box if the user has access %>
    <% if can? :read, Service %>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-yellow"><i class="fa fa-phone"></i></span>

        <div class="info-box-content">
          <span class="info-box-text">Services</span>
          <span class="info-box-number"><%= @phones_count %></span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <% end %>

  </div>
  <!-- /.row -->

  <!-- Main row -->
  <div class="row">
    <!-- Left col -->
    <div class="col-md-8 col-md-offset-2">
      <!-- MAP & BOX PANE -->
      <div class="box box-success">
        <div class="box-header with-border">
          <h3 class="box-title">Actions</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
          </div>
        </div>
        <!-- /.box-header -->

	<div class="box-body">
	  <div class="row">
	    <div class="col-md-5 col-md-offset-1">
              <% if can? :read, Client %>
		<%= link_to "#{icon 'user'} View Customer".html_safe, clients_path, class: 'btn btn-block btn-social btn-default btn-lg', style: "max-width:14em" %>
              <% end %>

              <% if can? :create, Client %>
		<%= link_to "#{icon 'user'} Add Customer".html_safe, new_client_path, class: 'btn btn-block btn-social btn-default btn-lg', style: "max-width:14em" %>
              <% end %>

              <% if can? :run_invoice, Client %>
		<%= link_to "#{icon 'dashboard'} Run Invoice".html_safe, '#', class: 'btn btn-block btn-social btn-default btn-lg', style: "max-width:14em" %>
              <% end %>

              <% if can? :process_payment, Client %>
		<%= link_to "#{icon 'dollar'} Process Payment".html_safe, '#', class: 'btn btn-block btn-social btn-default btn-lg', style: "max-width:14em", data: { toggle: 'modal', target: '.process-payment-modal' } %>
              <% end %>

	      <%= link_to "#{icon 'file'} Generate Report".html_safe, '#', class: 'btn btn-block btn-social btn-default btn-lg', style: "max-width:14em", onclick: 'alert("Not yet implemented.\nIn the future the report functions will be available here");' %>

	      <%= link_to "#{icon 'square'} Onetime Charge Export".html_safe, onetime_billable_services_path, class: 'btn btn-block btn-social btn-default btn-lg', style: "max-width:14em" %>

	      <%= link_to "#{icon 'square'} Charge Export".html_safe, exports_billable_services_path, class: 'btn btn-block btn-social btn-default btn-lg', style: "max-width:14em" %>


	      <%= link_to "#{icon 'square'} View Products".html_safe, products_path, class: 'btn btn-block btn-social btn-default btn-lg', style: "max-width:14em" %>





	    </div>
	  </div>
	</div>
      </div>
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
<% else %>
  <!-- Unauthorized row -->
  <div class="row">
    <!-- Left col -->
    <div class="col-md-6 col-md-offset-3">
      <!-- MAP & BOX PANE -->
      <div class="box box-danger" style="margin-top: 50px;">
        <div class="box-header with-border">
          <h3 class="box-title"><b>Why is this page empty?</b></h3>
        </div>
        <!-- /.box-header -->

        <div class="box-body ">
          <div class="row">
            <div class="col-sm-12">
              <p>You lack required privileges to access the data.</p>
              <p>
                If your account was made recently, this could be an error or
                your account is still pending confirmation.
              </p>
            </div>
          </div>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
<% end %>

<% if can? :read, Client %>
  <div class="modal view-customer-modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span></button>
          <h4 class="modal-title">Find Client</h4>
        </div>

        <%= form_tag '/clients', method: :get do %>
          <div class="modal-body">
            <input type="text" name="query" placeholder="Search query..." class="form-control">
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
            <%= submit_tag 'Go', class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>
<% end %>

<% if can? :read, Client %>
  <div class="modal process-payment-modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span></button>
          <h4 class="modal-title">Process Payment</h4>
        </div>

        <%= form_tag payment_process_dashboards_path, method: 'get' do %>
          <div class="modal-body">
              <div class="form-group">
                <%= label_tag :client_id %>
                <%= select_tag :client_id, nil, class: 'selectize payments' %>
              </div>

              <!-- <div class="form-group">
                <%# label_tag :btn_id %>
                <%# select_tag :btn_id, nil, class: 'selectize' %>
              </div> -->
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
            <%= submit_tag 'Process', class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>
<% end %>

templates/jb_src/app/views/dashboards/process_payment.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="box box-default">
      <div class="box-header">
	<h1 class="box-title"><%= @client.name %></h1>
      </div>

      <div class="box-body">
	<%= render 'payments/summary' %>
      </div>
    </div>

    <%= render 'payments/form' %>
  </div>
</div>